### ISSUE TITLE
Refactoring to got a calculation of adjustment relative to sight zero line

### ISSUE THREAD

**Issue by o-murphy** [o-murphy/py-ballisticcalc#46]

**Comment by o-murphy** [comment]
Wow, that's awesome. I'll check it soon

**Comment by dbookstaber** [comment]
I consider https://github.com/dbookstaber/py_ballistics/commit/b0cb39b487da2ee2f955e34316d425e62a04d07f to be a stable version.

The subsequent work I just checked in has exposed some things that I need to refine.

(In either commit you can follow the Example.ipynb to see how this works for now.)
