### ISSUE TITLE
Enforce sort order for winds

### ISSUE THREAD

**Issue by dbookstaber** [o-murphy/py-ballisticcalc#51]
In the case of multiple winds: `TrajectoryCalc` assumes that `Shot.winds[]` is sorted by `Wind.until_distance` (ascending).  However right now we do not enforce that or even check whether that assumption is valid.

What is the best way to handle this?

**Comment by o-murphy** [comment]
Is this done?

**Comment by dbookstaber** [comment]
No

**Comment by julius425** [comment]
Sorting can be done in Shot's __post_init__. 
Hey guys, im new to open source. Im not a math guy, but i like guns. Can i try to commit to your project?

**Comment by dbookstaber** [comment]
That would be great!  The process to contribute:

1. Fork the repository
2. Make changes
3. Ensure all unit tests pass
4. Commit your changes to your fork
5. Enter a "pull request" from your fork

Then the owner (@o-murphy) can review and accept your changes.

**Comment by o-murphy** [comment]
> Sorting can be done in Shot's **post_init**. Hey guys, im new to open source. Im not a math guy, but i like guns. Can i try to commit to your project?

it shouldn't be difficult, I think it can be done in one line, but I would do it with some setter method, cause Shot dataclass ain't frozen and we have to sort winds each times it changes
