### ISSUE TITLE
Commandline and TOML interfaces

### ISSUE THREAD

**Issue by dbookstaber** [o-murphy/py-ballisticcalc#64]
## Files
* DragTable: list of {Mach: Cd} pairs sorted by Mach ascending
* Weapon: [sight_height], [twist], [zero_elevation]
* Ammo: \<DragTable\>, \<BC\>, [powder_temp, temp_modifier]

*Problems:*

1. API expects Ammo to indicate muzzle velocity, but muzzle velocity depends on the Weapon, and also on Atmo.Temperature if temp_modifier is indicated.
2. Specification of how weapon is zeroed.  Shooters don't know their zero elevation (i.e., the angle between the barrel and sight line when scope is set to zero); what they know is zero distance for particular Ammo and Atmo.

## Commandline Args
* Angles (assume zero if not supplied)
  * Look-angle
  * Cant-angle
  * Holds
    * Vertical
    * Horizontal
* Atmospherics (assume standard if not supplied)
  * Temperature
  * Pressure
  * Altitude
  * Humidity
  * Wind {\<direction\> \<speed\>} ...
* Target:
  *  \<distance\> (if supplied then we will solve for hold angle to hit)
  *  \<height\> (if supplied then we will calculate danger space)
* Range (trajectory calculated to distance)
* Step (for tabular output)

**Comment by o-murphy** [comment]
Would not be implrmrnted
