### ISSUE TITLE
Can't instantiate Weapon with itself

### ISSUE THREAD

**Issue by dbookstaber** [o-murphy/py-ballisticcalc#68]
Trying to pass a Weapon instance to a new Shot:
```
zero = Shot(weapon=Weapon(sight_height=0), ammo=Ammo(DragModel(0.32, TableG7), mv=Velocity.FPS(1100)))
calc = Calculator()
zero_distance = Distance.Yard(100)
zero_elevation = calc.set_weapon_zero(zero, zero_distance)
s = Shot(zero.weapon, ammo=Ammo(DragModel(0.32, TableG7), mv=Velocity.FPS(1050)))
```

... produces a `TypeError`.

**Comment by julius425** [comment]
Its not a bug imo. 
In the first case you are passing Weapon instance as kwarg. 
`Shot(weapon=Weapon(...`
In the second case you pass Weapon instance without param name as look_angle param, that comes first in Shot's order of params.
`Shot(zero.weapon,...`

**Comment by dbookstaber** [comment]
Right you are – Good catch!
