### ISSUE TITLE
Can no longer adjust settings with 2.0.1 or 2.02

### ISSUE THREAD

**Issue by badders** [o-murphy/py-ballisticcalc#81]
**Describe the bug**

Can no longer import the settings module to configure default units. Also note that the documented example still imports this module: https://github.com/o-murphy/py-ballisticcalc?tab=readme-ov-file#units

**To Reproduce**

```
from py_ballisticcalc import Settings
```
This now throws the exception

cannot import name 'Settings' from 'py_ballisticcalc' 

**Expected behavior**

To work as it did in 1.x releases

**Environment: **
 - OS: Windows 11
 - Python3 version: 3.11.7
 - Release tested 2.0.1 and 2.0.2

**Comment by o-murphy** [comment]
Hi, @badders 

It is not bug. Yes now I see, the README have not adjusted to last changes. I'll publish fixed version soon

### In version 2.x.x we changed concepts of settings, there are 2 ways to set preferences

#### We refactored `Settings.Units` with `py_ballisticcalc.unit.PreferredUnits`

```python
from py_ballisticcalc import PreferredUnits

# set global library settings
PreferredUnits.velocity = Velocity.MPS
PreferredUnits.adjustment = Angular.Mil
PreferredUnits.temperature = Temperature.Celsius
PreferredUnits.distance = Distance.Meter
PreferredUnits.sight_height = Distance.Centimeter
PreferredUnits.drop = Distance.Centimeter
```

#### Other settings was refactored with global flags

```python
from from py_ballisticcalc import *

set_global_use_powder_sensitivity(True)

# Allowed this flags:
#  'get_global_max_calc_step_size',
#  'get_global_use_powder_sensitivity',
#  'set_global_max_calc_step_size',
#  'set_global_use_powder_sensitivity',
#  'reset_globals'
```

#### pybc.toml
Also u can use additional method to set preffered units/settings globally for the venv or the user.
You can create `.pybc.toml` or `pybc.toml` file in your project root directory (where venv was places)
Or place this file in `user's home directory`. _(The file in project root have priority.)_
[Reference there](https://github.com/o-murphy/py-ballisticcalc/blob/master/.pybc.toml)
[Additional there](https://github.com/o-murphy/py-ballisticcalc/tree/master/assets)
You can use `basicConfig()` function to load your custom `.toml` file

```python
from py_ballisticcalc import basicConfig

basicConfig("path/to/your_config.toml")
```
